### ISSUE TITLE
migrate from tfswitch to tenv

### ISSUE THREAD

**Issue by kvendingoldo** [ministryofjustice/opg-infra-costs-action#17]
Hi! I saw that you're using tfswitch. It does not support Terragrunt and OpenTofu, so, I suggest you to switch to tool that can manage all of these tools together: https://github.com/tofuutils/tenv

**Comment by charlesmmarshall** [comment]
Hi @kvendingoldo - apologies for the delay getting back to you. Thank you for suggesting this change. We currently do not use or support terragrunt or opentufu in our setup (which drove a lot of the development). The code in this repository will also be discontinued shortly and set as archived thereafter as we move to an alternative metric tool. 

Unfortunately, this means we won't be able to allocate resources to replace tfswitch in this case. It is licensed under MIT, so you are open to fork this codebase if you wish
